name: mvola
description: A MVola API client for dart and eventually flutter.
repository: https://github.com/tbgracy/mvola-dart
homepage: https://pub.dev/packages/mvola

version: 0.1.0-dev.3

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dotenv: ^4.0.1